### ISSUE TITLE
wpool:stop(my_pool) returns ok. but nothing exits

### ISSUE THREAD

**Issue by orotemo** [inaka/worker_pool#103]
after attempting to stop, I try to do `q().` but still, `ok`, and nothing exits.`wpool:stop()` just hangs.

Thanks in advance.

**Comment by elbrujohalcon** [comment]
That's because you're using `wpool:stop/1` which is a callback for the `application` behaviour instead of using `wpool:stop_pool/1` which is actually what you need.

**Comment by orotemo** [comment]
Hi, and thanks for the reply. however... I'd say this is not the standard behavior. stopping a node is now not possible, because `wpool:stop_pool/1` don't get called when worker_pool is a release dependency.

**Comment by elbrujohalcon** [comment]
@orotemo sorry, but I don't understand.

`wpool:stop_pool/1` will only stop one pool (and only if it was started with `wpool:start_sup_pool(…)`). If you need to stop them all you should use `application:stop(wpool)` which will effectively stop all pools since it will kill the supervisor that supervises them all.

Is there anything else you're trying to achieve and I'm missing here?
