### ISSUE TITLE
Worker recycling/expiration

### ISSUE THREAD

**Issue by igaray** [inaka/worker_pool#20]
Having long-lived processes which accept arbitrary work from others may lead to resource leaks. It would be good to give the workers the ability to decide to die after a certain configurable period of time and/or tasks and be re-spawned, in order to have their garbage collected.

**Comment by jfacorro** [comment]
+1

**Comment by jaynel** [comment]
The main reason that trips long-lived processes is the use of 3rd party software especially which leaves entries in the process dictionary. They can cause failure on future executions when there is a conflict in keys and prior values.

When expiring workers, it is better to have stochastic decay so that you don't have a herd of replacements that get synchronized. You want to stagger relaunch so that you have even pressure on resources.

The last issue relates to memory leaks and memory allocation / fragmentation. Periodically recycling ensures you don't leave behind things, especially in the process dictionary which will never get collected unless the keys are deleted. But there may also be heap issues if you have data which the processes keep around (e.g., a gen_server which has a state and accepts requests).

**Comment by elbrujohalcon** [comment]
@igaray it's not entirely intuitive, but you can achieve the same effect with something like [this](https://github.com/elbrujohalcon/rwp).
What you actually need to do is:

1. Set [a proper supervisor strategy](https://github.com/elbrujohalcon/rwp/blob/master/src/rwp.erl#L15) like ``{one_for_one, 1000, 1}`` when you start the pool
2. Use `gen_server`'s [default timeout mechanism](https://github.com/elbrujohalcon/rwp/blob/master/src/rwp_worker.erl#L33) to let your workers die when they're inactive.

Do you think that's enough?

**Comment by jaynel** [comment]
Not following. What restarts a worker that stops with 'normal'?

**Comment by elbrujohalcon** [comment]
The supervisor, workers are permanent by definition.

**Comment by jaynel** [comment]
So every 5 seconds, idle workers would restart? As long as the pool is busy, no impact, and during idle/less busy times, the supervisor does more spawning. A completely idle system would be spawning all pool workers continuously?

**Comment by elbrujohalcon** [comment]
In my dumb example, yes. But the point is you can do whatever you want by just using supervisor strategy and gen_server timeouts appropriately

**Comment by igaray** [comment]
I agree that it can be done this way, with proper configuration of the child specs. Documentation and examples would be more important if we leave it up to the library user to set it up correctly. I'll close the issue and we can write a blog post.
